# 打印性能信息  
profiler = "log/rail.prof"

#http监听端口
http_listen = 8888

#队列扫描定时器相关配置
queue_scan_worker_pool_max = 4
queue_scan_selection_count = 4
queue_scan_interval_ms = 100
queue_scan_refresh_interval_sec = 1
queue_scan_dirty_percent = 0.25




[backend]
data_path = "var"
max_bytes_per_file = 111111
max_msg_size = 1000000
sync_every = 100
sync_timeout = 1

[canal]
data_path = "var"

[log]
path = "log/rail.log"
# 0 单个文件 1按天分 2按小时分
type = 2
highlighting = false
level = "debug"

#定义订阅的mysql主库的连接信息
[mysql]
addr = "127.0.0.1:3306"
user = "root"
password = "123456"

[topic]
name = "topic1"
#topic缓存消息的池子大小
mem_buff_size = 1000   
 