#http监听端口
http_listen = 2060

#binlog position flush到磁盘的间隔
binlog_flush_ms = 2000  #2s刷新一次

#队列扫描定时器相关配置
queue_scan_worker_pool_max = 4
queue_scan_selection_count = 4
queue_scan_interval_ms = 100
queue_scan_refresh_interval_sec = 1
queue_scan_dirty_percent = 0.25

[backend]
#the directory of keeping data of disk queue and  master.info 
data_path = "var"
#128M
max_bytes_per_file = 134217728
#10M
max_msg_size = 10485760
sync_every = 100
#unit:second
sync_timeout = 1

[log]
path = "log/rail.log"
# 0 单个文件 1按天分 2按小时分
type = 2
highlighting = false
level = "debug"

#定义订阅的mysql主库的连接信息
[mysql]
addr = "127.0.0.1:3306"
user = "root"
password = "123456"
#mariadb or mysql
flavor = "mysql"  

[topic]
name = "mytopic"
schema = "test"
table = "test"
#topic缓存消息的池子大小
mem_buff_size = 1000

 
